---
title: "Brucellosis sso
ciations"
author: "Kahariri"
date: "`r Sys.Date()`"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# You do not need to set a working directory for a 
#setwd("C:/Users/Skahariri/kahariri Dropbox/samuel kahariri/phd/Time series Analysis")
# import packages
library(pacman)
p_load(tidyverse)
p_load(sf)
p_load(lme4)
p_load(tsibble)
p_load(fabletools)
p_load(fable)
p_load(fma)
p_load(MTS) # For multivariable ARIMA
p_load(tseries)
p_load(vars)
p_load(urca)
p_load(mFilter)
p_load(forecast)
#p_load(MASS)
```



```{r zones}
## agro-ecological zones
agro_zones <- read_csv("data/agro-eco_zone/eco_zones_county.csv")
# Cleaning Ecological zones

agro_zones <- agro_zones |>
  mutate(county = ifelse(county == "Elgeiyo Marakwet", "Elgeyo Marakwet", county))
#setdiff(eco_zones$county, df_cum$county)

# Cleaning the ecological zones
df_zones = agro_zones |>
  mutate(
    split1 =  str_split(agro_zones$eco_zone, ";", simplify = T)[, 1] |> str_squish(),
    split2 =  str_split(agro_zones$eco_zone, ";", simplify = T)[, 2] |> str_squish(),
    farming = ifelse(split1 == "Farming" |
                       split2 == "Farming", 1, 0),
    agropastoral = ifelse(split1 == "Agropastoral" |
                            split2 == "Agropastoral", 1, 0),
    pastoral = ifelse(split1 == "Pastoral" |
                        split2 == "Pastoral", 1, 0),
    fishing = ifelse(split1 == "Fishing" |
                       split2 == "Fishing", 1, 0),
    riverine = ifelse(split1 == "Riverine" |
                        split2 == "Riverine", 1, 0),
  ) |>
  dplyr::select(-eco_zone,-split1,-split2)

# Creating the zones as factors and defining the reference level
df_zones <- df_zones %>%
  mutate(across(
    c(farming, agropastoral, fishing, riverine, pastoral),
    ~ relevel(factor(
      .x, levels = c(0, 1), labels = c("No", "Yes")
    ), ref = "No")
  ))

```



```{r human data cleaning}

# Importing data
human_pop <- read_csv("pop_14-21.csv")

# Cleaning data
human_pop_kenya <- human_pop |> 
  group_by(year) |> 
  summarise(pop = sum(pop))

## human data
total_human_zoonoses <-
  read_csv("Zoonosis_2014_2021_county.csv") %>%
  janitor::clean_names() %>%
  mutate(organisationunitname = str_remove(organisationunitname, "County")) %>%
  mutate(organisationunitname = trimws(organisationunitname)) %>%
  dplyr::rename(county = organisationunitname) %>%
  pivot_longer(
    cols = c(
      "brucellosis",
      "moh_705a_rev_2020_rift_valley_fever",
      "moh_705a_rev_2020_suspected_anthrax",
      "moh_706_brucella"
    ),
    names_to = "diseases",
    values_to = "disease_values"
  ) %>%
  mutate(
    diseases = recode(
      diseases,
      "moh_705a_rev_2020_rift_valley_fever" = "Rvf",
      "moh_705a_rev_2020_suspected_anthrax" = "Anthrax",
      "moh_706_brucella" = "Brucella"
    )
  ) %>%
  mutate(diagnosis = ifelse(diseases %in% "Brucella", "Laboratory", "Clinical")) %>%
  dplyr::select(periodname, county, diseases, disease_values, diagnosis) %>%
  mutate(diseases = recode(diseases, "Brucella" = "brucellosis")) |> 
  mutate(date = dmy(paste0("01", "-", periodname))) %>%
  filter(!date < "2014-01-01") %>%
  #filter(!is.na(disease_values)) %>%
  dplyr::select(date, county, diseases, disease_values, diagnosis) |> 
  mutate(species = "Human") %>%
  mutate(county = recode(county, "Muranga" = "Murang'a")) %>%
  filter(diseases %in% "brucellosis")  |> 
  #group_by(date, county) %>%
  #mutate(total_human=disease_values) %>%
  #ungroup() %>%
  left_join(df_zones, by = "county") %>%
  mutate(year = str_sub(date, 1, 4)) %>%
  mutate(year = as.numeric(year)) %>%
  left_join(human_pop, by = c("year", "county"))

# Zoonoses
human_zoonoses <- total_human_zoonoses %>%
  group_by(date, county, species) %>%
  mutate(disease_values = sum(disease_values, na.rm = T)) %>%
  dplyr::select(-diagnosis) %>%
  distinct() %>%
  mutate(incidence = round(disease_values / pop * 100000)) %>%
  distinct() %>% 
  ungroup() %>% 
  dplyr::select(-diseases, -species)

human_zoonoses_dx <- total_human_zoonoses %>%
  mutate(incidence = round(disease_values / pop * 100000)) %>%
  distinct()

kenya_human_zoonoses <- human_zoonoses |> 
  select(date, county, disease_values, pop) |> 
  group_by(date) |> 
  summarise(hum_cases = sum(disease_values),
            ) |> 
  mutate(year = year(date)) |> 
  merge(human_pop_kenya, by = "year") |> 
  select(-year) |> 
  mutate(human_incidence = hum_cases/pop*1e3)

```



```{r, animal}

animal_pop <- read_csv('animal_pop_2019.csv') %>% 
  pivot_wider(
    names_from = "species",
    values_from = "species_num"
  ) %>% 
  setNames(c("county", paste0(colnames(.[,2:7]), "_pop") %>% str_to_lower()))

kenya_animal_pop <- animal_pop |> 
  summarise(across(where(is.numeric), ~sum(.))) |> 
  select(-donkeys_pop, -pigs_pop)

## animal data
total_animal_zoonoses <- read_csv("animal_zoonoses.csv") %>%
  dplyr::select(date, county, disease_condition,species, no_sick, diagnosis) %>%
  mutate(date = lubridate::ymd(date)) %>%
  #dplyr::rename(animal_diagnosis=diagnosis)%>%
  filter(disease_condition %in% "Brucellosis") |> 
  distinct()

animal_zoonoses <-  total_animal_zoonoses %>%
  group_by(date, county, species) %>%
  summarise(total_animal = sum(no_sick, na.rm = T)) |>
  mutate(
    species = str_to_sentence(species),
    species = case_when(
      str_detect(species, "bovine|Bovine") ~ "Cattle",
      str_detect(species, "Ovine|ovine") ~ "Sheep",
      str_detect(species, "caprine|Caprine") ~ "Goats",
      TRUE ~ species
    ),
    total_animal = as.numeric(total_animal)
  ) |> 
  filter(species %in% c("Cattle", "Sheep", "Goats", "Camel")) |> 
  distinct() |> 
  ungroup() |> 
    pivot_wider(
      id_cols = c("date", "county"),
    values_from = total_animal,
    names_from = species
  ) |> 
  distinct()

animal_zoonoses_dx <- total_animal_zoonoses |> 
  mutate(
    species = str_to_sentence(species),
    species = case_when(
      str_detect(species, "bovine|Bovine") ~ "Cattle",
      str_detect(species, "Ovine|ovine") ~ "Sheep",
      str_detect(species, "caprine|Caprine") ~ "Goats",
      TRUE ~ species
    ),
    no_sick = as.numeric(no_sick)
  ) |> 
  filter(species %in% c("Cattle", "Sheep", "Goats", "Camel")) |> 
  distinct() |> 
  pivot_wider(
    id_cols = c("date", "county", "diagnosis"),
    values_from = no_sick,
    names_from = species,
    values_fn = list(no_sick = sum)  # Use values_fn to summarize duplicates
  )



kenya_animal_zoonoses <- animal_zoonoses |> 
  group_by(date) |> 
  summarise(across(where(is.numeric), ~sum(., na.rm = T))) |> 
  mutate(across(where(is.numeric), ~ifelse(. == 0, NA, .)))

```

```{r combining}

brucellosis_kenya <- kenya_animal_zoonoses |>
  merge(kenya_human_zoonoses, by = "date") |>
  cbind(kenya_animal_pop) |>
  mutate(
    catt_incidence = round((Cattle / cattle_pop) * 1000000, 4),
    cam_incidence = round((Camel / camels_pop) * 1000000, 4),
    goat_incidence = round((Goats / goats_pop) * 1000000, 4),
    shp_incidence = round((Sheep / sheep_pop) * 1000000, 4)
  ) |> 
  ungroup()

brucellosis_kenya_combined <- brucellosis_kenya |> 
  rowwise() |> 
  mutate(
    animal_pop = sum(cattle_pop, sheep_pop, camels_pop, goats_pop),
    animal_cases = sum(Cattle, Sheep, Camel, Goats),
    animal_incidence = animal_cases/animal_pop*1e6
  ) |> 
  ungroup() |> 
  select(date, animal_cases, animal_pop, animal_incidence, human_incidence, pop)


library(data.table)

brucellosis <- animal_zoonoses %>% 
  merge(human_zoonoses, by = c("county", "date"), all = T) %>% 
  merge(animal_pop, by = "county") %>% 
  mutate(
    catt_incidence = round((Cattle / cattle_pop) * 1000000, 4),
    cam_incidence = round((Camel / camels_pop) * 1000000, 4),
    goat_incidence = round((Goats / goats_pop) * 1000000, 4),
    shp_incidence = round((Sheep / sheep_pop) * 1000000, 4)
  ) %>% 
  mutate(human_incidence = incidence) |> 
  distinct()

brucellosis_full <- animal_zoonoses_dx %>% 
  merge(human_zoonoses_dx, by = c("county", "date", "diagnosis"), all = T) %>% 
  merge(animal_pop, by = "county") %>% 
  mutate(
    catt_incidence = round((Cattle / cattle_pop) * 1000000, 4),
    cam_incidence = round((Camel / camels_pop) * 1000000, 4),
    goat_incidence = round((Goats / goats_pop) * 1000000, 4),
    shp_incidence = round((Sheep / sheep_pop) * 1000000, 4)
  ) %>% 
  mutate(human_incidence = incidence) |> 
  distinct() |> 
  rename(c(hum_cases = disease_values,
            catt_cases = Cattle,
            goat_cases = Goats,
            shp_cases = Sheep,
            cam_cases = Camel,
           catt_pop = cattle_pop,
           hum_pop = pop,
           cam_pop = camels_pop,
           goat_pop = goats_pop
           ))

write.csv(brucellosis_full, "all_bruc_incidence2.csv")

brucellosis_total <- brucellosis %>% 
  rowwise() %>% 
  mutate(animal_cases = sum(Cattle, Camel, Goats, Sheep, na.rm = T),
         animal_pop = sum(cattle_pop, camels_pop, goats_pop, sheep_pop, na.rm = T),
         animal_incidence = animal_cases/animal_pop*1e6
         ) %>% 
  dplyr::select(date, county, animal_incidence, human_incidence)
 
```


```{r individual species}

brucellosis_kenya_cattle_goats <- brucellosis_kenya |>
  select(date, catt_incidence, goat_incidence, human_incidence) |>
  mutate(
      lag1_catt_incidence = lag(catt_incidence, n = 1),
      lag2_catt_incidence = lag(catt_incidence, n = 2), 
      lag3_catt_incidence = lag(catt_incidence, n = 3),
      
      lag1_goat_incidence = lag(goat_incidence, n = 1),
      lag2_goat_incidence = lag(goat_incidence, n = 2), 
      lag3_goat_incidence = lag(goat_incidence, n = 3)
  ) |> 
  as_tsibble()

# At lag 0
df_1_trend_complete %>%
  as_tsibble() |> 
  model(TSLM(human_incidence ~ catt_incidence + goat_incidence)) %>%
  report() 

# At lag 1
brucellosis_kenya_cattle_goats %>%
   filter(!is.na(lag1_catt_incidence) & lag1_catt_incidence > 0) |> 
  model(TSLM(human_incidence ~ lag1_catt_incidence + lag1_goat_incidence)) %>%
  report() 

# At lag 2
brucellosis_kenya_cattle_goats %>%
  filter(!is.na(lag2_catt_incidence)) |> 
  model(TSLM(human_incidence ~ lag2_catt_incidence + lag2_goat_incidence)) %>%
  report() 

# At lag 3
brucellosis_kenya_cattle_goats %>%
  filter(!is.na(lag3_catt_incidence)) |> 
  model(TSLM(human_incidence ~ lag3_catt_incidence + lag3_goat_incidence)) %>%
  report() 
```


```{r combined species}

# lag 0 #0.056
brucellosis_kenya_combined %>%
  as_tsibble() |> 
model(TSLM(human_incidence~animal_incidence)) %>%
  report() 

# lag 1 # 0.0338
brucellosis_kenya_combined %>%
  filter(!is.na(lag1_animal)) |>
  as_tsibble() |>
  model(TSLM(human_incidence ~ lag1_animal)) %>%
  report()

# lag 2 ##P value 0.0688
brucellosis_kenya_combined %>%
  filter(!is.na(lag2_animal)) |>
  as_tsibble() |>
  model(TSLM(human_incidence ~ lag2_animal)) %>%
  report()

# lag 3 ##P value 0.0784
brucellosis_kenya_combined %>%
  filter(!is.na(lag3_animal)) |>
  as_tsibble() |>
  model(TSLM(human_incidence ~ lag3_animal)) %>%
  report()

```


```{r}
## agro-ecological zone
bruc_agro <- brucellosis %>%
  dplyr::select(date, eco_zone, incidence)%>%
  distinct()%>%
  group_by(date, eco_zone) %>%
  mutate(total_human=sum(incidence, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence)%>%
  distinct() 
ts_bruc_eco<- as_tsibble(bruc_agro, validate=F, index = date)
# lag 0
ts_bruc_eco %>%
model(TSLM(total_human~eco_zone)) %>%
  report()


```

```{r}
## clinical data for animals

bruc_clinical <- brucellosis %>%
  dplyr::select(date, total_animal,animal_diagnosis,eco_zone, incidence)%>%
  filter(animal_diagnosis%in%"Clinically confirmed")%>%
  distinct()%>%
  group_by(date) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence, -animal_diagnosis)%>%
  distinct() %>%
  mutate(lag1_animal=lag(total_animal, n=1))%>%
  mutate(lag2_animal=lag(total_animal, n=2)) %>%
  mutate(lag3_animal=lag(total_animal, n=3))%>%
  mutate(lag4_animal=lag(total_animal, n=4))

ts_bruc_clinical<- as_tsibble(bruc_clinical, validate=F, index = date)
# lag 0
ts_bruc_clinical %>%
model(TSLM(total_human~total_animal)) %>%
  report()
# lag 1 # 0.248
ts_bruc_clinical %>%
model(TSLM(total_human~lag1_animal)) %>%
  report()
# lag 2 ##P value 0.25
ts_bruc_clinical %>%
model(TSLM(total_human~lag2_animal)) %>%
  report()
# lag 3 ##P value 0.183
ts_bruc_clinical %>%
model(TSLM(total_human~lag3_animal)) %>%
  report()

  # lag 4 ##P value 0.124
ts_bruc_clinical %>%
model(TSLM(total_human~lag4_animal)) %>%
  report()
```


```{r}
## lab data for animals

bruc_lab <- brucellosis %>%
  dplyr::select(date, total_animal,animal_diagnosis,eco_zone, incidence)%>%
  filter(animal_diagnosis%in%"Lab confirmed")%>%
  distinct()%>%
  group_by(date) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence, -animal_diagnosis)%>%
  distinct() %>%
  mutate(lag1_animal=lag(total_animal, n=1))%>%
  mutate(lag2_animal=lag(total_animal, n=2)) %>%
  mutate(lag3_animal=lag(total_animal, n=3))%>%
  mutate(lag4_animal=lag(total_animal, n=4))

ts_bruc_lab<- as_tsibble(bruc_lab, validate=F, index = date)
# lag 0 <0.001
model<-ts_bruc_lab %>%
model(TSLM(total_human~total_animal)) %>%
  report()
# lag 1 # <0.001
ts_bruc_lab %>%
model(TSLM(total_human~lag1_animal)) %>%
  report()
# lag 2 ##P value <0.001
ts_bruc_lab %>%
model(TSLM(total_human~lag2_animal)) %>%
  report()
# lag 3 ##P value <0.001
ts_bruc_lab %>%
model(TSLM(total_human~lag3_animal)) %>%
  report()

  # lag 4 ##P value 0.124
ts_bruc_clinical %>%
model(TSLM(total_human~lag4_animal)) %>%
  report()
```

```{r}
## species data for animals: cattle
 
bruc_cattle <- brucellosis %>%
  dplyr::select(date, total_animal,species.x, eco_zone, incidence)%>%
  filter(species.x%in%"Bovine")%>%
  distinct()%>%
  group_by(date) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence, -species.x)%>%
  distinct() %>%
  mutate(lag1_animal=lag(total_animal, n=1))%>%
  mutate(lag2_animal=lag(total_animal, n=2)) %>%
  mutate(lag3_animal=lag(total_animal, n=3))%>%
  mutate(lag4_animal=lag(total_animal, n=4))

ts_bruc_cattle<- as_tsibble(bruc_cattle, validate=F, index = date)
# lag 0 <0.001
ts_bruc_cattle %>%
model(TSLM(total_human~total_animal)) %>%
  report()
# lag 1 # <0.001
ts_bruc_cattle %>%
model(TSLM(total_human~lag1_animal)) %>%
  report()
# lag 2 ##P value <0.001
ts_bruc_cattle %>%
model(TSLM(total_human~lag2_animal)) %>%
  report()
# lag 3 ##P value <0.001
ts_bruc_cattle %>%
model(TSLM(total_human~lag3_animal)) %>%
  report()

  # lag 4 ##P value 0.124
ts_bruc_cattle %>%
model(TSLM(total_human~lag4_animal)) %>%
  report() 
```


```{r}
## species data for animals: camel
 
bruc_camel <- brucellosis %>%
  dplyr::select(date, total_animal,species.x, eco_zone, incidence)%>%
  filter(species.x%in%"Camel")%>%
  distinct()%>%
  group_by(date) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence, -species.x)%>%
  distinct() %>%
  mutate(lag1_animal=lag(total_animal, n=1))%>%
  mutate(lag2_animal=lag(total_animal, n=2)) %>%
  mutate(lag3_animal=lag(total_animal, n=3))%>%
  mutate(lag4_animal=lag(total_animal, n=4))

ts_bruc_camel<- as_tsibble(bruc_camel, validate=F, index = date)
# lag 0 0.6257 
ts_bruc_camel %>%
model(TSLM(total_human~total_animal)) %>%
  report()
# lag 1 # <0.866
ts_bruc_camel %>%
model(TSLM(total_human~lag1_animal)) %>%
  report()
# lag 2 ##P value <2e-16
ts_bruc_camel %>%
model(TSLM(total_human~lag2_animal)) %>%
  report()
# lag 3 ##P value 0.667
ts_bruc_camel %>%
model(TSLM(total_human~lag3_animal)) %>%
  report()

  # lag 4 ##P value 0.124
ts_bruc_camel %>%
model(TSLM(total_human~lag4_animal)) %>%
  report() 
```

```{r}
# species data for animals: small ruminant

bruc_smallruminant <- brucellosis %>%
  mutate(species.x= ifelse(species.x %in% c("Caprine", "Ovine"), "Small ruminants", "species.x"))%>%
  dplyr::select(date, total_animal,species.x, eco_zone, incidence)%>%
  filter(species.x%in%"Small ruminants")%>%
  distinct()%>%
  group_by(date) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence, -species.x)%>%
  distinct() %>%
  mutate(lag1_animal=lag(total_animal, n=1))%>%
  mutate(lag2_animal=lag(total_animal, n=2)) %>%
  mutate(lag3_animal=lag(total_animal, n=3))%>%
  mutate(lag4_animal=lag(total_animal, n=4))

ts_bruc_sheep<- as_tsibble(bruc_smallruminant, validate=F, index = date)
# lag 0 <0.62339
ts_bruc_sheep %>%
model(TSLM(total_human~total_animal)) %>%
  report()
# lag 1 # 0.955
ts_bruc_sheep %>%
model(TSLM(total_human~lag1_animal)) %>%
  report()
# lag 2 ##P value 0.62158
ts_bruc_sheep %>%
model(TSLM(total_human~lag2_animal)) %>%
  report()
# lag 3 ##P value 0.71655 
ts_bruc_sheep %>%
model(TSLM(total_human~lag3_animal)) %>%
  report()

  # lag 4 ##P value 0.6976
ts_bruc_sheep %>%
model(TSLM(total_human~lag4_animal)) %>%
  report() 
```


```{r}
## species data for animals: goats
 
bruc_goat <- brucellosis %>%
  dplyr::select(date, total_animal,species.x, incidence)%>%
  filter(species.x%in%"Caprine")%>%
  distinct()%>%
  group_by(date) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence, -species.x)%>%
  distinct() %>%
  mutate(lag1_animal=lag(total_animal, n=1))%>%
  mutate(lag2_animal=lag(total_animal, n=2)) %>%
  mutate(lag3_animal=lag(total_animal, n=3))%>%
  mutate(lag4_animal=lag(total_animal, n=4))

ts_bruc_goat<- as_tsibble(bruc_goat, validate=F, index = date)
# lag 0  0.812 
ts_bruc_goat %>%
model(TSLM(total_human~total_animal)) %>%
  report()
# lag 1 # 0.754
ts_bruc_goat %>%
model(TSLM(total_human~lag1_animal)) %>%
  report()
# lag 2 ##P value 0.712
ts_bruc_goat %>%
model(TSLM(total_human~lag2_animal)) %>%
  report()
# lag 3 ##P value 0.822
ts_bruc_goat %>%
model(TSLM(total_human~lag3_animal)) %>%
  report()

  # lag 4 ##P value 0.946
ts_bruc_goat %>%
model(TSLM(total_human~lag4_animal)) %>%
  report() 
```



```{r}
## Moving Averages
###############################################################
## I have corrected this, do the same for the ones below.

##Human~spp AVG
bruc_avg <- brucellosis %>%
  dplyr::select(date, total_animal, incidence)%>%
  distinct()%>%
  group_by(date) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence)%>%
  distinct() %>%
  mutate(mo1_animal=zoo::rollmean(total_animal, k=1, fill=NA))%>%
  mutate(mo2_animal=zoo::rollmean(total_animal, k=2, fill=NA)) %>%
  mutate(mo3_animal=zoo::rollmean(total_animal, k=3, fill=NA))

ts_bruc_avg<- as_tsibble(bruc_avg, validate=T, index = date)
# Mvg Avg 1
ts_bruc_avg %>%
model(TSLM(total_human~mo1_animal)) %>%
  report()

# Mvg Avg 2
ts_bruc_avg %>%
model(TSLM(total_human~mo2_animal)) %>%
  report()

# Mvg Avg 3

ts_bruc_avg %>%
model(TSLM(total_human~mo3_animal)) %>%
  report()

```


```{r}
## agro-ecological zone
bruc_avg_ez <- bruc_avg <- brucellosis %>%
  dplyr::select(date, total_animal, incidence, eco_zone)%>%
  distinct()%>%
  group_by(date, eco_zone) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence)%>%
  distinct() %>%
  mutate(mo1_animal=zoo::rollmean(total_animal, k=1, fill=NA))%>%
  mutate(mo2_animal=zoo::rollmean(total_animal, k=2, fill=NA)) %>%
  mutate(mo3_animal=zoo::rollmean(total_animal, k=3, fill=NA))%>%
  distinct()

 
ts_bruc_avg_ez<- as_tsibble(bruc_avg_ez, validate=F, index = date)

ts_bruc_avg_ez %>%
model(TSLM(total_human~eco_zone)) %>%
  report()

#######################################################################
#Human~ animal species

bruc_avg_spp <- bruc_avg <- brucellosis %>%
  dplyr::select(date, total_animal, incidence, eco_zone, species.x)%>%
  distinct()%>%
  group_by(date, species.x) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence)%>%
  distinct() #%>%
 
ts_bruc_avg_spp<- as_tsibble(bruc_avg_spp, validate=F, index = date)


ts_bruc_avg_spp %>%
model(TSLM(total_human~species.x)) %>%
  report()



```





```{r}
## Multivariable

bruc_comb <- brucellosis %>%
  dplyr::select(date, species.x, total_animal, incidence, eco_zone)%>%
  distinct()%>%
  group_by(date, eco_zone) %>%
  mutate(total_human=sum(incidence, na.rm=T),
         total_animal=sum(total_animal, na.rm=T)) %>%
  ungroup()%>%
  dplyr::select(-incidence)%>%
  distinct() %>%
  mutate(lag1_animal=lag(total_animal, n=1))%>%
  mutate(lag2_animal=lag(total_animal, n=2)) %>%
  mutate(lag3_animal=lag(total_animal, n=3))%>%
  mutate(lag4_animal=lag(total_animal, n=4))%>%
  mutate(mo1_animal=zoo::rollmean(total_animal, k=1, fill=NA))%>%
  mutate(mo2_animal=zoo::rollmean(total_animal, k=2, fill=NA)) %>%
  mutate(mo3_animal=zoo::rollmean(total_animal, k=3, fill=NA))

ts_bruc_comb<- as_tsibble(bruc_comb, validate=F, index = date)

#Human~ecozone +lag0
# Adjusted R squared= 0.3937
ts_bruc_comb %>%
model(TSLM(total_human~total_animal+eco_zone)) %>%
  report()

#Human~ecozone +lag1
# Adjusted R squared= 0.3709
ts_bruc_comb %>%
model(TSLM(total_human~lag1_animal+eco_zone)) %>%
  report()
##Human~ecozone +lag2
# Adjusted R squared= 0.3884
ts_bruc_comb %>%
model(TSLM(total_human~lag2_animal+eco_zone)) %>%
  report()

#Human~ecozone + species
# Adjusted R squared= 0.2491
ts_bruc_comb %>%
model(TSLM(total_human~eco_zone+species.x)) %>%
  report()



```


```{r}




 
#ts_bruc_avg_ez<- as_tsibble(bruc_avg_ez, validate=F, index = date)

#ts_bruc_avg_ez<- zoo::read.zoo(bruc_avg_ez)

#Human~ecozone +avg1
# Adjusted R squared= 0.3937
ts_bruc_comb %>%
model(TSLM(total_human~eco_zone+mo1_animal)) %>%
  report()
##Human~ecozone +avg2
# Adjusted R squared=  0.4108
ts_bruc_comb %>%
model(TSLM(total_human~eco_zone+mo2_animal)) %>%
  report()

#Human~ecozone + avg3
# Adjusted R squared= 0.4125
ts_bruc_comb %>%
model(TSLM(total_human~eco_zone+mo3_animal)) %>%
  report()
```



```{r}
# Forecast
bruc_data1 <- bruc_comb %>%
  dplyr::select(date, total_human,eco_zone,mo3_animal)%>%
 # group_by(date)%>%
#  mutate(total_human=sum(total_human, na.rm=T))%>%
 # ungroup()%>%
  distinct()

ts_bruc_data1 <- as_tsibble(bruc_data1, validate=F, index = date, key=eco_zone)
autoplot(ts_bruc_data1)#+facet_grid()

model2 <- ts_bruc_data1 %>%
model(lm=TSLM(total_human~mo3_animal),
      arima=ARIMA(total_human),
       ets=ETS(total_human)
      )




future_scenarios <-new_data(ts_bruc_data1, n=10)
future_scenarios$mo3_animal <- sample(ts_bruc_data1[!is.na(ts_bruc_data1$mo3_animal),]$mo3_animal, 50)
#future_scenarios$eco_zone <- sample(ts_bruc_data1$eco_zone, 50)
future_scenarios <- future_scenarios %>%
  group_by(eco_zone) %>%
  mutate(date=seq.Date(from=as.Date("2022-01-01"),  by="1 month", length.out=10))

future_scenarios<- distinct(future_scenarios)

future_scenarios <- as_tsibble(future_scenarios,validate = T,  index = date, key=eco_zone)


forecast_data <- fabletools::forecast(model, new_data=future_scenarios)


ts_bruc_data1 %>%
  fabletools::autoplot(total_human) +
  fabletools::autolayer(forecast_data[forecast_data$.model%in%"lm2",])+
  facet_grid(eco_zone~.)+
  theme_bw()

ggsave("ts_all_bruc.png", width=16, height=9)


### tests for seasonality
isSeasonal(ts_bruc_data1$total_human, freq = 96)
```

```{r, multivariable_ARIMA}

# combined data

bruc_combined_data <- bruc_comb %>%
  dplyr:: select(date,eco_zone,total_human,  mo1_animal) %>%
  distinct() %>%
  arrange(date) %>%
  mutate(eco_zone=as.numeric(recode(eco_zone, "Agropastoral"="1", "Farming"="2", "Fishing"="3", "Pastoral"="4", "Riverine"="5")))
 # filter(eco_zone=="Agropastoral") %>%
#  dplyr::select(-date, -eco_zone)

ts_data <- as_tsibble(bruc_combined_data, key=eco_zone, index=date)

stnry = diffM(ts_data[, 3])

var1 <- vars::VAR(ts_data, p=2, ic="AIC")

bruc_combined_data_1 <- bruc_comb %>%
  dplyr:: select(date,eco_zone,total_human,  mo1_animal) %>%
  distinct() %>%
  arrange(date) %>%
  filter(eco_zone=="Farming") %>%
  dplyr::select(-date, -eco_zone)


ts_bruc_combined_data2 <- ts(bruc_combined_data_1, frequency=12, start=c(2014,1), end=c(2021,12))

plot(ts_bruc_combined_data2)

apply(bruc_combined_data, 2, adf.test)

stnry = diffM(ts_bruc_combined_data2) #difference operation on a vector of time series. Default order of differencing is 1.
apply(stnry, 2, adf.test)

plot(stnry)

bruc_comb1 <- bruc_comb %>%
  dplyr:: select(eco_zone,total_human,  mo1_animal) %>%
  filter(eco_zone=="Farming") %>%
  dplyr::select(-eco_zone) %>%
  #mutate(mo3_animal=is.na(mo3_animal),0,mo3_animal) %>%
  distinct()

bruc_comb1a <- bruc_comb %>%
  dplyr:: select(eco_zone,total_human,  mo2_animal) %>%
  filter(eco_zone=="Farming") %>%
  dplyr::select(-eco_zone) %>%
  #mutate(mo3_animal=is.na(mo3_animal),0,mo3_animal) %>%
  distinct()




ts_bruc_comb1 <- ts(bruc_comb1, frequency=12, start=c(2014,1))
ts_bruc_comb1a <- ts(bruc_comb1a, frequency=12, start=c(2014,1))
#ts_bruc_comb1b <- ts(bruc_comb1b, frequency=12, start=c(2014,1))

 
#apply(ts_bruc_comb1, 2, adf.test)

#farm <- diffM(bruc_comb1)
# <- diffM(bruc_comb1a)
#farm2 <- diffM(ts_bruc_comb1b)

#var.a <- vars::VAR(stnry,ic="AIC", type="none")
#farm1a <- MTS::VAR(stnry1)


#VARpred(farm1a,2)

##############################################
# Farming Eco zone
bruc_farm <- bruc_comb %>%
  dplyr:: select(eco_zone,total_human,  mo3_animal) %>%
  filter(eco_zone=="Farming") %>%
  dplyr::select(-eco_zone) %>%
  mutate(mo3_animal=is.na(mo3_animal),0,mo3_animal) %>%
  distinct()

ts_bruc_farm <- ts(bruc_farm, frequency=12, start=c(2014,1))

apply(ts_bruc_farm, 2, adf.test)

farm <- diffM(bruc_farm)

farm1 <- MTS::VAR(farm)


# Agropastoral eco_zone

bruc_agro <- bruc_comb %>%
  dplyr:: select(eco_zone,total_human,  mo2_animal) %>%
  filter(eco_zone=="Agropastoral") %>%
  dplyr::select(-eco_zone) %>%
  distinct()

ts_bruc_agro <- ts(bruc_agro, frequency=12, start=c(2014,1))

apply(ts_bruc_agro, 2, adf.test)

agro <- diffM(bruc_agro)

agro1 <- MTS::VAR(agro)

# Fishing eco_zone
bruc_fish <- bruc_comb %>%
  dplyr:: select(eco_zone,total_human,  mo2_animal) %>%
  filter(eco_zone=="Fishing") %>%
  dplyr::select(-eco_zone) %>%
  distinct()

ts_bruc_fish <- ts(bruc_fish, frequency=12, start=c(2014,1))

apply(ts_bruc_fish, 2, adf.test)

fish <- diffM(bruc_fish)

fish1 <- MTS::VAR(fish)

# Pastoral eco zone

bruc_past <- bruc_comb %>%
  dplyr:: select(eco_zone,total_human,  mo2_animal) %>%
  filter(eco_zone=="Pastoral") %>%
  dplyr::select(-eco_zone) %>%
  distinct()

ts_bruc_past <- ts(bruc_past, frequency=12, start=c(2014,1))

apply(ts_bruc_past, 2, adf.test)

past <- diffM(bruc_past)

past1 <- MTS::VAR(past)

# Riverrine eco_zone

bruc_river <- bruc_comb %>%
  dplyr:: select(eco_zone,total_human,  mo2_animal) %>%
  filter(eco_zone=="Riverine") %>%
  dplyr::select(-eco_zone) %>%
  distinct()%>%
  mutate(mo2_animal=!is.na(mo2_animal))

ts_bruc_river <- ts(bruc_past, frequency=12, start=c(2014,1))

apply(ts_bruc_river, 2, adf.test)

river <- diffM(bruc_river)

river1 <- MTS::VAR(river)

# Plotting the forecast
##################################################################################
bruc_comb1b <- bruc_comb %>%
  dplyr:: select(eco_zone,total_human,  mo3_animal) %>%
  filter(eco_zone=="Farming") %>%
  dplyr::select(-eco_zone) %>%
  mutate(mo3_animal=is.na(mo3_animal),0,mo3_animal) %>%
  distinct()

ts_bruc_farm1 <- ts(bruc_comb1b, frequency=12, start=c(2014,1))

## Lag selection
lagselect <- VARselect(ts_bruc_farm1, lag.max = 12
                       , type = "const")
lagselect$selection

## Building VAR
model_farm <- VAR(ts_bruc_farm1, p = 1, type = "const", season = NULL, exog = NULL)

summary(model_farm)
```





